import { Routes } from '@angular/router';
import { CustomerShell } from './layouts/customer-shell.component';
import { AdminShell } from './layouts/admin-shell.component';
import { authGuard, guestGuard, staffGuard, permissionGuard } from './core/guards/auth.guard';

export const routes: Routes = [
  {
    path: '',
    pathMatch: 'full',
    loadComponent: () => import('./features/home/home.component').then((m) => m.HomePage),
  },
  {
    path: 'admin',
    children: [
      {
        path: 'login',
        canActivate: [guestGuard],
        loadComponent: () => import('./features/admin/admin-login.component').then((m) => m.AdminLoginPage),
      },
      {
        path: '',
        component: AdminShell,
        canActivate: [staffGuard],
        children: [
          { path: 'denied', loadComponent: () => import('./features/admin/denied.component').then((m) => m.DeniedPage) },
          { path: 'dashboard', loadComponent: () => import('./features/admin/dashboard/dashboard.component').then((m) => m.DashboardPage), canActivate: [permissionGuard('dashboard:read')] },
          { path: 'flights', loadComponent: () => import('./features/admin/flights/flights.component').then((m) => m.FlightsPage), canActivate: [permissionGuard('flights:read')] },
          { path: 'airports', loadComponent: () => import('./features/admin/catalog/airports.component').then((m) => m.AirportsPage), canActivate: [permissionGuard('airports:manage')] },
          { path: 'aircraft', loadComponent: () => import('./features/admin/catalog/aircraft.component').then((m) => m.AircraftPage), canActivate: [permissionGuard('aircraft:manage')] },
          { path: 'routes', loadComponent: () => import('./features/admin/catalog/routes.component').then((m) => m.RoutesPage), canActivate: [permissionGuard('routes:manage')] },
          { path: 'bookings', loadComponent: () => import('./features/admin/ops/admin-bookings.component').then((m) => m.AdminBookingsPage), canActivate: [permissionGuard('bookings:read')] },
          { path: 'users', loadComponent: () => import('./features/admin/ops/admin-users.component').then((m) => m.AdminUsersPage), canActivate: [permissionGuard('users:read')] },
          { path: 'staff', loadComponent: () => import('./features/admin/ops/admin-staff.component').then((m) => m.AdminStaffPage), canActivate: [permissionGuard('staff:manage')] },
          { path: 'roles', loadComponent: () => import('./features/admin/ops/admin-roles.component').then((m) => m.AdminRolesPage), canActivate: [permissionGuard('roles:manage')] },
          { path: 'payments', loadComponent: () => import('./features/admin/ops/admin-payments.component').then((m) => m.AdminPaymentsPage), canActivate: [permissionGuard('payments:read')] },
          { path: 'refunds', loadComponent: () => import('./features/admin/ops/admin-refunds.component').then((m) => m.AdminRefundsPage), canActivate: [permissionGuard('payments:refund')] },
          { path: 'baggage', loadComponent: () => import('./features/admin/ops/admin-baggage.component').then((m) => m.AdminBaggagePage), canActivate: [permissionGuard('baggage:manage')] },
          { path: 'checkin', loadComponent: () => import('./features/admin/ops/admin-checkin.component').then((m) => m.AdminCheckInPage), canActivate: [permissionGuard('checkin:manage')] },
          { path: 'loyalty', loadComponent: () => import('./features/admin/ops/admin-loyalty.component').then((m) => m.AdminLoyaltyPage), canActivate: [permissionGuard('loyalty:manage')] },
          { path: 'notifications', loadComponent: () => import('./features/admin/ops/admin-notifications.component').then((m) => m.AdminNotificationsPage), canActivate: [permissionGuard('notifications:manage')] },
          { path: 'reports', loadComponent: () => import('./features/admin/ops/admin-reports.component').then((m) => m.AdminReportsPage), canActivate: [permissionGuard('reports:read')] },
          { path: 'audit', loadComponent: () => import('./features/admin/ops/admin-audit.component').then((m) => m.AdminAuditPage), canActivate: [permissionGuard('audit:read')] },
          { path: 'settings', loadComponent: () => import('./features/admin/ops/admin-settings.component').then((m) => m.AdminSettingsPage), canActivate: [permissionGuard('settings:manage')] },
          { path: '', pathMatch: 'full', redirectTo: 'dashboard' },
        ],
      },
    ],
  },
  {
    path: '',
    component: CustomerShell,
    children: [
      { path: 'search', loadComponent: () => import('./features/customer/booking/search.component').then((m) => m.SearchPage) },
      { path: 'offers', loadComponent: () => import('./features/customer/offers/offers.component').then((m) => m.OffersPage) },
      { path: 'results', loadComponent: () => import('./features/customer/booking/results.component').then((m) => m.ResultsPage) },
      { path: 'flights/:id', loadComponent: () => import('./features/customer/booking/flight-details.component').then((m) => m.FlightDetailsPage) },
      { path: 'booking/passengers', loadComponent: () => import('./features/customer/booking/passengers.component').then((m) => m.PassengersPage) },
      { path: 'booking/seats', loadComponent: () => import('./features/customer/booking/seats.component').then((m) => m.SeatsPage) },
      { path: 'booking/extras', loadComponent: () => import('./features/customer/booking/extras.component').then((m) => m.ExtrasPage) },
      { path: 'booking/review', loadComponent: () => import('./features/customer/booking/review.component').then((m) => m.ReviewPage) },
      { path: 'booking/confirmation', loadComponent: () => import('./features/customer/booking/confirmation.component').then((m) => m.ConfirmationPage) },
      { path: 'login', loadComponent: () => import('./features/customer/auth/login.component').then((m) => m.LoginPage), canActivate: [guestGuard] },
      { path: 'register', loadComponent: () => import('./features/customer/auth/register.component').then((m) => m.RegisterPage), canActivate: [guestGuard] },
      { path: 'forgot-password', loadComponent: () => import('./features/customer/auth/forgot-password.component').then((m) => m.ForgotPasswordPage), canActivate: [guestGuard] },
      { path: 'reset-password', loadComponent: () => import('./features/customer/auth/reset-password.component').then((m) => m.ResetPasswordPage), canActivate: [guestGuard] },
      { path: 'verify-email', loadComponent: () => import('./features/customer/auth/verify-email.component').then((m) => m.VerifyEmailPage) },
      { path: 'bookings', loadComponent: () => import('./features/customer/account/my-bookings.component').then((m) => m.MyBookingsPage), canActivate: [authGuard] },
      { path: 'bookings/:id', loadComponent: () => import('./features/customer/trips/manage-booking.component').then((m) => m.ManageBookingPage), canActivate: [authGuard] },
      { path: 'manage', loadComponent: () => import('./features/customer/trips/manage-lookup.component').then((m) => m.ManageLookupPage) },
      { path: 'checkin', loadComponent: () => import('./features/customer/trips/checkin.component').then((m) => m.CheckInPage) },
      { path: 'checkin/:bookingId/pass', loadComponent: () => import('./features/customer/trips/boarding-pass.component').then((m) => m.BoardingPassPage) },
      { path: 'status', loadComponent: () => import('./features/customer/trips/flight-status.component').then((m) => m.FlightStatusPage) },
      { path: 'baggage', loadComponent: () => import('./features/customer/trips/baggage.component').then((m) => m.BaggagePage) },
      { path: 'loyalty', loadComponent: () => import('./features/customer/account/loyalty.component').then((m) => m.LoyaltyPage), canActivate: [authGuard] },
      { path: 'profile', loadComponent: () => import('./features/customer/account/profile.component').then((m) => m.ProfilePage), canActivate: [authGuard] },
      { path: 'profile/:section', loadComponent: () => import('./features/customer/account/profile.component').then((m) => m.ProfilePage), canActivate: [authGuard] },
      { path: 'help', loadComponent: () => import('./features/customer/help.component').then((m) => m.HelpPage) },
      { path: '', pathMatch: 'full', redirectTo: 'search' },
    ],
  },
  { path: '**', loadComponent: () => import('./features/customer/help.component').then((m) => m.HelpPage) },
];
